apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  database-url: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9tZXNzYWdpbmdfZGI=  # base64 encoded
  secret-key: YmFzZTY0LWVuY29kZWQtc2VjcmV0LWtleS1oZXJl  # base64 encoded
